// Pure Markdown report generator. Turns a runScan `result` into a portable
// .md document (scores, AI-readiness lenses, top issues with plain-language
// explanations, per-page table, trackers) — reused by the report route and
// any future export. Reads the existing result/signals shape; computes nothing.

import { questsFromIssues } from "./gamify";
import { EXPLANATIONS } from "./explanations";

const LENS_ROWS = [
  ["aeo", "AEO — Answer Engine"],
  ["geo", "GEO — Generative Engine"],
  ["aio", "AIO — AI Overviews"],
  ["ago", "AGO — Agent Access"],
];

function grade(s) {
  if (s == null) return "—";
  if (s >= 90) return "A";
  if (s >= 75) return "B";
  if (s >= 60) return "C";
  if (s >= 40) return "D";
  return "F";
}

const n = (v) => (v == null ? "—" : v);

// Make a string safe to drop into a Markdown table cell.
function cell(s) {
  return String(s ?? "").replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

export function generateMarkdownReport(result, { generatedAt } = {}) {
  const pages = result.pages || [];
  const ai = result.aiReadiness;
  const layers = ai?.layers || {};
  const blocked = ai?.site?.botsBlocked || [];
  const host = (() => {
    try {
      return new URL(result.rootUrl).host;
    } catch {
      return result.rootUrl || "site";
    }
  })();

  const out = [];
  out.push(`# SEO & AI-Search Audit — ${host}`, "");
  out.push(`- **Scanned:** ${result.rootUrl}`);
  if (result.redirected && result.requestedUrl) {
    out.push(`- **Redirected from:** ${result.requestedUrl}`);
  }
  if (generatedAt) out.push(`- **Generated:** ${generatedAt}`);
  out.push(`- **Pages analyzed:** ${pages.length}`, "");

  // Scores
  out.push("## Scores", "");
  out.push("| Metric | Score | Grade |", "| --- | --- | --- |");
  out.push(`| SEO health | ${n(result.siteScore)} | ${grade(result.siteScore)} |`);
  out.push(`| AI readiness | ${n(ai?.overall)} | ${grade(ai?.overall)} |`, "");

  out.push("### AI readiness by lens", "");
  out.push("| Lens | Score |", "| --- | --- |");
  for (const [key, label] of LENS_ROWS) out.push(`| ${label} | ${n(layers[key])} |`);
  out.push("");
  if (blocked.length) out.push(`> ⚠ AI crawlers blocked: ${blocked.join(", ")}`, "");

  // Top issues (merge classic + AI issues across pages, grouped by rule)
  const allIssues = pages.flatMap((p) => [
    ...(p.audit?.issues || []),
    ...(p.aiAudit?.issues || []),
  ]);
  const grouped = questsFromIssues(allIssues).slice(0, 15);

  out.push("## Top issues", "");
  if (grouped.length === 0) {
    out.push("No issues found — clean audit. 🎉", "");
  } else {
    grouped.forEach((g, i) => {
      const ex = EXPLANATIONS[g.ruleKey] || {};
      out.push(`### ${i + 1}. ${g.title}`);
      out.push(
        `- **Severity:** ${g.severity} · **Affects:** ${g.pagesAffected} page(s) · **Category:** ${g.category}`
      );
      if (ex.what) out.push(`- **What it means:** ${ex.what}`);
      if (ex.why) out.push(`- **Why it matters:** ${ex.why}`);
      if (g.recommendation) out.push(`- **How to fix:** ${g.recommendation}`);
      out.push("");
    });
  }

  // Pages
  out.push("## Pages", "");
  out.push(
    "| URL | Status | SEO | Grade | Errors | Warnings |",
    "| --- | --- | --- | --- | --- | --- |"
  );
  for (const p of pages) {
    const c = p.audit?.counts || {};
    out.push(
      `| ${cell(p.url)} | ${n(p.httpStatus)} | ${n(p.audit?.score)} | ${grade(p.audit?.score)} | ${n(c.error)} | ${n(c.warning)} |`
    );
  }
  out.push("");

  // Trackers
  const tools = result.analytics?.tools || [];
  out.push("## Trackers detected", "");
  if (tools.length === 0) out.push("None detected.", "");
  else {
    for (const t of tools) out.push(`- ${t.name || t.key}${t.heatmap ? " (heatmap)" : ""}`);
    out.push("");
  }

  out.push("---", "_Generated by MadRank — SEO & AI-search audit._", "");
  return out.join("\n");
}
